### PR TITLE
Feature/resume playback

### PR DESCRIPTION
**Pull request by IvayloAtanasov**
Playback can now be resumed from the server time if song was paused. 
Replaced plain iframe player with iframe using the youtube iframe api.
There is a slight problem with handling on player state change event. I've used a flag to go around the problem but there may be a better solution.

### CODE REVIEW

**Comment by Bratanov** [comment]
Related to: https://github.com/Bratanov/community-driven-radio/issues/1

**Comment by Bratanov** [comment]
To see @Yavor-Ivanov's changes without the line endings messing up for review see this: https://github.com/Bratanov/community-driven-radio/pull/13/files/d79214eda6b764ae3dc90966ce4e45c1f4a1aae4..cee576d4ddf7fa4ca50f2444c2d51fd4470f9022

**Comment by Bratanov** [comment]
Changes from: https://github.com/Bratanov/community-driven-radio/pull/19 and https://github.com/Bratanov/community-driven-radio/pull/17 got somehow included in the latest changes. I'll clean those up when I get the chance so they're separated as functionalities and test (on @IvayloAtanasov's fork directly), after that it's good to go.

**Comment by Yavor-Ivanov** [comment]
@Bratanov Whoops! Also, this is why I disike git flow. Looks like I created the branch from something other than `master` without noticing. Not sure what to do about those except double check next time :(.

**Comment by Bratanov** [comment]
On a second though this is fine the way it is, will merge to keep the party going.

**Pull request merged**
